title = "Gitleaks configuration"

[extend]
useDefault = true

[[allowlists]]
description = "global allow list"
paths = [
    '''backend/test/Integration/Service.Tests/TestConstants.cs''',
    '''backend/test/Integration/Service.Tests/Utilities/cert/*'''
]